feat: add build status badges

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -58,6 +58,41 @@ jobs:
           echo "::set-output name=short_ref::${BRANCHTRANSLATED}"
           echo "::set-output name=sha_short::SHA-$(git rev-parse --short=12 HEAD)"
           echo "::set-output name=version::${VERSION}"
+      - name: Ensure Badges branch exists
+        run: |
+          BRANCH_NAME=badges
+
+          # make sure we've got all branches from the remote
+          # fetched locally before we call `git show-branch`
+          # (actions/checkout does not fetch all branches)
+          git fetch
+
+
+          # check if the branch already exists
+          if git show-branch "remotes/origin/$BRANCH_NAME"; then
+              echo "INFO: branch $BRANCH_NAME already exists, exiting..."
+              exit 0
+          fi
+
+          # if it doesn't exist, create one
+          echo "INFO: branch $BRANCH_NAME does not exist, creating a new orphan branch..."
+
+          # store the currently checked out branch before we start
+          CURRENT_BRANCH=$(git branch --show-current)
+          [ -z "$CURRENT_BRANCH" ] && echo "ERROR: I don't know how to cleanup, exiting..." && exit 1
+
+          # create the orphan branch and push it
+          git checkout --orphan "$BRANCH_NAME"
+          git rm -rf .
+          rm -f '.gitignore'
+          echo "# $BRANCH_NAME" > README.md
+          git add README.md
+          git commit -m 'init'
+          git push origin "$BRANCH_NAME"
+
+          # cleanup
+          git checkout --force "$CURRENT_BRANCH"
+
   build:
     name: Build
     needs: refs
@@ -83,6 +118,26 @@ jobs:
       - run: ls -la
       - name: Run make
         run: make APP_VERSION=${{ needs.refs.outputs.version }} APP_NAME=${{ matrix.platform }} ${{ matrix.platform }}
+      - name: Write Failed Badge
+        uses: action-badges/core@0.2.2
+        if: failure() && needs.refs.outputs.new_release == 'true' && (github.ref == 'refs/heads/main' || github.ref_name == 'alpha')
+        with:
+          file-name: build-${{ matrix.platform }}.svg
+          github-token: "${{ secrets.GITHUB_TOKEN }}"
+          badge-branch: badges
+          label: ${{ matrix.platform }}
+          message: build failing
+          message-color: red
+      - name: Write Badge
+        uses: action-badges/core@0.2.2
+        if: needs.refs.outputs.new_release == 'true' && (github.ref == 'refs/heads/main' || github.ref_name == 'alpha')
+        with:
+          file-name: build-${{ matrix.platform }}.svg
+          github-token: "${{ secrets.GITHUB_TOKEN }}"
+          badge-branch: badges
+          label: ${{ matrix.platform }}
+          message: ${{ needs.refs.outputs.version }}
+          message-color: green        
       - name: Save build assets
         uses: actions/upload-artifact@v2
         with:
