fix(ci): make sure badges branch exists

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -27,10 +27,6 @@ jobs:
           submodules: recursive        
       - name: Update SDKs if required
         run: make update-submodules
-      - name: Ensure badges brach exists
-        uses: action-badges/create-orphan-branch@0.1.0
-        with:
-          branch-name: badges              
       - name: Semantic Release
         id: semantic
         uses: cycjimmy/semantic-release-action@v2
@@ -61,6 +57,40 @@ jobs:
           echo "::set-output name=short_ref::${BRANCHTRANSLATED}"
           echo "::set-output name=sha_short::SHA-$(git rev-parse --short=12 HEAD)"
           echo "::set-output name=version::${VERSION}"
+      - name: Ensure Badges branch exists
+        run: |
+          export $BRANCH_NAME=badges
+
+          # make sure we've got all branches from the remote
+          # fetched locally before we call `git show-branch`
+          # (actions/checkout does not fetch all branches)
+          git fetch
+
+
+          # check if the branch already exists
+          if git show-branch "remotes/origin/$BRANCH_NAME"; then
+              echo "INFO: branch $BRANCH_NAME already exists, exiting..."
+              exit 0
+          fi
+
+          # if it doesn't exist, create one
+          echo "INFO: branch $BRANCH_NAME does not exist, creating a new orphan branch..."
+
+          # store the currently checked out branch before we start
+          CURRENT_BRANCH=$(git branch --show-current)
+          [ -z "$CURRENT_BRANCH" ] && echo "ERROR: I don't know how to cleanup, exiting..." && exit 1
+
+          # create the orphan branch and push it
+          git checkout --orphan "$BRANCH_NAME"
+          git rm -rf .
+          rm -f '.gitignore'
+          echo "# $BRANCH_NAME" > README.md
+          git add README.md
+          git commit -m 'init'
+          git push origin "$BRANCH_NAME"
+
+          # cleanup
+          git checkout --force "$CURRENT_BRANCH"
 
   build:
     name: Build
